github.com:
    users:
        m1126stryker:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: m1126stryker
